DROP DATABASE IF EXISTS htblog;
CREATE DATABASE IF NOT EXISTS htblog;
USE htblog;

CREATE TABLE medium(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(255) NOT NULL DEFAULT 'img/jpeg',
  path VARCHAR(255) NOT NULL DEFAULT 'default.jpg'
) ENGINE InnoDB DEFAULT CHAR SET utf8;

CREATE TABLE users(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nicknake VARCHAR(255) NOT NULL DEFAULT '',
  realname VARCHAR(255) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  password TEXT,
  intro TEXT,
  signature VARCHAR(255) NOT NULL DEFAULT '',
  picture VARCHAR(255) DEFAULT 'default.jpg',
  created_at DATETIME,
  updated_at DATETIME
) ENGINE InnoDB DEFAULT CHAR SET utf8;
